### ISSUE TITLE
Changing the width of bins in the frequency histogram

### ISSUE THREAD

**Issue by RujiSun** [Bartesto/ScatMatch#3]
I need to adjust the width of the bin but I cannot do it with the package. I currently use this to get the bin size of each mm (mismatch number).

hist(dis_list$dist,
     xlab = "No. of mismatch",
     ylab = "Frequency",
     labels = TRUE,
     breaks = -1:max(dis_list$dist))

**Comment by Bartesto** [comment]
Have added a "bins" parameter for user control. Defaults to 30. Addressed in commit commit b5de1172e9eac66aa87cb311a14c4f1397664ce7
